spring:
  application:
    name: dagagomap
  jpa:
    open-in-view: false
  threads:
    virtual:
      enabled: true

custom:
  kakao:
    local:
      semaphore-limit: 100
  public-data:
    page-size: 100
