spring:
  application:
    name: dagagomap
  jpa:
    open-in-view: false
  main:
    keep-alive: true
  threads:
    virtual:
      enabled: true
  web:
    error:
      include-stacktrace: never
      include-exception: false
      include-message: never

custom:
  kakao:
    local:
      concurrency-limit: 100
  public-data:
    page-size: 100
